[package]
name = "module_8"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0"
jsonwebtoken = "8.1"
serde = { version = "1.0", features = ["derive"] }
futures-util = "0.3"
